// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System.Collections.Generic;

	public static class Archetypes
	{
		public const int Bullet1_a15f0809f29cbf74c99418d4581ffc2cIndex = 0;
		public const int Bullet2_7ed8c4dd2d3496548b9b77dbfdabead6Index = 1;
		public const int CFX_Flash_a81ef04ac72436744a08ef117fa691b4Index = 2;
		public const int CFXR__char_32_Explosion__char_32_3__char_32___char_43___char_32_Text__char_32_1_e528427daa147834a9cc58aaf27ec7c2Index = 3;
		public const int EnemySpawner_deb987f02f3b9c5438adee8e7657523eIndex = 4;
		public const int Enemy_a112f92c18af08a4cb206e6b4611b41fIndex = 5;
		public const int El__char_32_Grenado_d2d154794ac855841a82a46b05bb7869Index = 6;
		public const int Player_0965159253ec9e3429357a3d7625b08fIndex = 7;

		public static Dictionary<string, int> IndexForName = new Dictionary<string, int>() {
			{ "Bullet1_a15f0809f29cbf74c99418d4581ffc2c", 0 },

			{ "Bullet2_7ed8c4dd2d3496548b9b77dbfdabead6", 1 },

			{ "CFX_Flash_a81ef04ac72436744a08ef117fa691b4", 2 },

			{ "CFXR__char_32_Explosion__char_32_3__char_32___char_43___char_32_Text__char_32_1_e528427daa147834a9cc58aaf27ec7c2", 3 },

			{ "EnemySpawner_deb987f02f3b9c5438adee8e7657523e", 4 },

			{ "Enemy_a112f92c18af08a4cb206e6b4611b41f", 5 },

			{ "El__char_32_Grenado_d2d154794ac855841a82a46b05bb7869", 6 },

			{ "Player_0965159253ec9e3429357a3d7625b08f", 7 },

		};
	}
}
