// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using UnityEngine;
	using Coherence.Toolkit;
	using Coherence.Toolkit.Bindings;
	using Coherence.Entity;
	using Coherence.ProtocolDef;
	using Coherence.Brook;
	using Coherence.Toolkit.Bindings.ValueBindings;
	using Coherence.Toolkit.Bindings.TransformBindings;
	using Coherence.Connection;
	using Coherence.Log;
	using Logger = Coherence.Log.Logger;
	using UnityEngine.Scripting;


	[Preserve]
	[AddComponentMenu("coherence/Baked/Baked 'Enemy' (auto assigned)")]
	[RequireComponent(typeof(CoherenceSync))]
	public class CoherenceSyncEnemy_id5 : CoherenceSyncBaked
	{
		private CoherenceSync coherenceSync;
		private Logger logger;

		// Cached targets for commands		
		private Enemy.EnemyBehavior Enemy_id5_Enemy__char_46_EnemyBehavior__char_46_SetValue_3348272d_be70_4d5b_b481_9b8126faac39_CommandTarget;

		private IClient client;
		private CoherenceMonoBridge monoBridge => coherenceSync.MonoBridge;

		protected void Awake()
		{
			coherenceSync = GetComponent<CoherenceSync>();
			coherenceSync.usingReflection = false;

			logger = coherenceSync.logger.With<CoherenceSyncEnemy_id5>();
			if (coherenceSync.TryGetBindingByGuid("3348272d-be70-4d5b-b481-9b8126faac39", "SetValue", out Binding Enemy_id5_Enemy__char_46_EnemyBehavior__char_46_SetValue_3348272d_be70_4d5b_b481_9b8126faac39))
			{
				Enemy_id5_Enemy__char_46_EnemyBehavior__char_46_SetValue_3348272d_be70_4d5b_b481_9b8126faac39_CommandTarget = (Enemy.EnemyBehavior)Enemy_id5_Enemy__char_46_EnemyBehavior__char_46_SetValue_3348272d_be70_4d5b_b481_9b8126faac39.UnityComponent;
				coherenceSync.AddCommandRequestDelegate("Enemy.EnemyBehavior.SetValue", "(System.Int32System.Boolean)",
				SendCommand_Enemy_id5_Enemy__char_46_EnemyBehavior__char_46_SetValue_3348272d_be70_4d5b_b481_9b8126faac39, ReceiveLocalCommand_Enemy_id5_Enemy__char_46_EnemyBehavior__char_46_SetValue_3348272d_be70_4d5b_b481_9b8126faac39, MessageTarget.All, Enemy_id5_Enemy__char_46_EnemyBehavior__char_46_SetValue_3348272d_be70_4d5b_b481_9b8126faac39_CommandTarget,false);
			}
			else
			{
				logger.Error("Couldn't find command binding (SetValue)");
			}
		}

		public override List<ICoherenceComponentData> CreateEntity()
		{
			if (coherenceSync.UsesLODsAtRuntime && (Archetypes.IndexForName.TryGetValue(coherenceSync.Archetype.ArchetypeName, out int archetypeIndex)))
			{
				var components = new List<ICoherenceComponentData>()
				{
					new ArchetypeComponent
					{
						index = archetypeIndex
					}
				};

				return components;
			}
			else
			{
				logger.Warning($"Unable to find archetype {coherenceSync.Archetype.ArchetypeName} in dictionary. Please, bake manually (coherence > Bake)");
			}

			return null;
		}

		public override void Initialize(CoherenceSync sync, IClient client)
		{
			if (coherenceSync == null)
			{
				coherenceSync = sync;
			}
			this.client = client;
		}
		void SendCommand_Enemy_id5_Enemy__char_46_EnemyBehavior__char_46_SetValue_3348272d_be70_4d5b_b481_9b8126faac39(MessageTarget target, object[] args)
		{
			var command = new Enemy_id5_Enemy__char_46_EnemyBehavior__char_46_SetValue_3348272d_be70_4d5b_b481_9b8126faac39();
			int i = 0;
			command.val = (int)((System.Int32)args[i++]);
			command.auth = (bool)((System.Boolean)args[i++]);
			client.SendCommand(command, target, coherenceSync.EntityID);
		}

		void ReceiveLocalCommand_Enemy_id5_Enemy__char_46_EnemyBehavior__char_46_SetValue_3348272d_be70_4d5b_b481_9b8126faac39(MessageTarget target, object[] args)
		{
			var command = new Enemy_id5_Enemy__char_46_EnemyBehavior__char_46_SetValue_3348272d_be70_4d5b_b481_9b8126faac39();
			int i = 0;
			command.val = (int)((System.Int32)args[i++]);
			command.auth = (bool)((System.Boolean)args[i++]);
			ReceiveCommand_Enemy_id5_Enemy__char_46_EnemyBehavior__char_46_SetValue_3348272d_be70_4d5b_b481_9b8126faac39(command);
		}

		void ReceiveCommand_Enemy_id5_Enemy__char_46_EnemyBehavior__char_46_SetValue_3348272d_be70_4d5b_b481_9b8126faac39(Enemy_id5_Enemy__char_46_EnemyBehavior__char_46_SetValue_3348272d_be70_4d5b_b481_9b8126faac39 command)
		{
			var target = Enemy_id5_Enemy__char_46_EnemyBehavior__char_46_SetValue_3348272d_be70_4d5b_b481_9b8126faac39_CommandTarget;
			target.SetValue((System.Int32)(command.val),(System.Boolean)(command.auth));
		}

		public override void ReceiveCommand(IEntityCommand command)
		{
			switch(command)
			{
				case Enemy_id5_Enemy__char_46_EnemyBehavior__char_46_SetValue_3348272d_be70_4d5b_b481_9b8126faac39 castedCommand:
					ReceiveCommand_Enemy_id5_Enemy__char_46_EnemyBehavior__char_46_SetValue_3348272d_be70_4d5b_b481_9b8126faac39(castedCommand);
					break;
				default:
					logger.Warning($"[CoherenceSyncEnemy_id5] Unhandled command: {command.GetType()}.");
					break;
			}
		}
	}
}
