// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using UnityEngine;
	using Coherence.Toolkit;
	using Coherence.Toolkit.Bindings;
	using Coherence.Entity;
	using Coherence.ProtocolDef;
	using Coherence.Brook;
	using Coherence.Toolkit.Bindings.ValueBindings;
	using Coherence.Toolkit.Bindings.TransformBindings;
	using Coherence.Connection;
	using Coherence.Log;
	using Logger = Coherence.Log.Logger;
	using UnityEngine.Scripting;

	public class Binding_0965159253ec9e3429357a3d7625b08f_cd50857d_f6f4_4ed5_ac69_9ffd378e192f : Vector3Binding
	{
		private UnityEngine.Rigidbody CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.Rigidbody)UnityComponent;
		}
		public override string CoherenceComponentName => "Player_UnityEngine__char_46_Rigidbody_2358891834408612276";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Vector3 Value
		{
			get => (Vector3)(UnityEngine.Vector3)(CastedUnityComponent.velocity);
			set => CastedUnityComponent.velocity = (UnityEngine.Vector3)(value);
		}

		protected override Vector3 ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Player_UnityEngine__char_46_Rigidbody_2358891834408612276)coherenceComponent;
			return update.velocity;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Player_UnityEngine__char_46_Rigidbody_2358891834408612276)coherenceComponent;
			update.velocity = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Player_UnityEngine__char_46_Rigidbody_2358891834408612276();
		}
	}

	public class Binding_0965159253ec9e3429357a3d7625b08f_60c3a288_cc2e_422e_ac67_bb3a0875fd71 : Vector3Binding
	{
		private UnityEngine.Rigidbody CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.Rigidbody)UnityComponent;
		}
		public override string CoherenceComponentName => "Player_UnityEngine__char_46_Rigidbody_2358891834408612276";

		public override uint FieldMask => 0b00000000000000000000000000000010;

		public override Vector3 Value
		{
			get => (Vector3)(UnityEngine.Vector3)(CastedUnityComponent.angularVelocity);
			set => CastedUnityComponent.angularVelocity = (UnityEngine.Vector3)(value);
		}

		protected override Vector3 ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Player_UnityEngine__char_46_Rigidbody_2358891834408612276)coherenceComponent;
			return update.angularVelocity;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Player_UnityEngine__char_46_Rigidbody_2358891834408612276)coherenceComponent;
			update.angularVelocity = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Player_UnityEngine__char_46_Rigidbody_2358891834408612276();
		}
	}


	[Preserve]
	[AddComponentMenu("coherence/Baked/Baked 'Player' (auto assigned)")]
	[RequireComponent(typeof(CoherenceSync))]
	public class CoherenceSyncPlayer : CoherenceSyncBaked
	{
		private CoherenceSync coherenceSync;
		private Logger logger;

		// Cached targets for commands

		private IClient client;
		private CoherenceMonoBridge monoBridge => coherenceSync.MonoBridge;

		protected void Awake()
		{
			coherenceSync = GetComponent<CoherenceSync>();
			coherenceSync.usingReflection = false;

			logger = coherenceSync.logger.With<CoherenceSyncPlayer>();
			if (coherenceSync.TryGetBindingByGuid("cd50857d-f6f4-4ed5-ac69-9ffd378e192f", "velocity", out Binding InternalPlayer_UnityEngine__char_46_Rigidbody_2358891834408612276_Player_UnityEngine__char_46_Rigidbody_2358891834408612276_velocity))
			{
				var clone = new Binding_0965159253ec9e3429357a3d7625b08f_cd50857d_f6f4_4ed5_ac69_9ffd378e192f();
				InternalPlayer_UnityEngine__char_46_Rigidbody_2358891834408612276_Player_UnityEngine__char_46_Rigidbody_2358891834408612276_velocity.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalPlayer_UnityEngine__char_46_Rigidbody_2358891834408612276_Player_UnityEngine__char_46_Rigidbody_2358891834408612276_velocity)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Rigidbody).velocity");
			}
			if (coherenceSync.TryGetBindingByGuid("60c3a288-cc2e-422e-ac67-bb3a0875fd71", "angularVelocity", out Binding InternalPlayer_UnityEngine__char_46_Rigidbody_2358891834408612276_Player_UnityEngine__char_46_Rigidbody_2358891834408612276_angularVelocity))
			{
				var clone = new Binding_0965159253ec9e3429357a3d7625b08f_60c3a288_cc2e_422e_ac67_bb3a0875fd71();
				InternalPlayer_UnityEngine__char_46_Rigidbody_2358891834408612276_Player_UnityEngine__char_46_Rigidbody_2358891834408612276_angularVelocity.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalPlayer_UnityEngine__char_46_Rigidbody_2358891834408612276_Player_UnityEngine__char_46_Rigidbody_2358891834408612276_angularVelocity)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Rigidbody).angularVelocity");
			}
		}

		public override List<ICoherenceComponentData> CreateEntity()
		{
			if (coherenceSync.UsesLODsAtRuntime && (Archetypes.IndexForName.TryGetValue(coherenceSync.Archetype.ArchetypeName, out int archetypeIndex)))
			{
				var components = new List<ICoherenceComponentData>()
				{
					new ArchetypeComponent
					{
						index = archetypeIndex
					}
				};

				return components;
			}
			else
			{
				logger.Warning($"Unable to find archetype {coherenceSync.Archetype.ArchetypeName} in dictionary. Please, bake manually (coherence > Bake)");
			}

			return null;
		}

		public override void Initialize(CoherenceSync sync, IClient client)
		{
			if (coherenceSync == null)
			{
				coherenceSync = sync;
			}
			this.client = client;
		}

		public override void ReceiveCommand(IEntityCommand command)
		{
			switch(command)
			{
				default:
					logger.Warning($"[CoherenceSyncPlayer] Unhandled command: {command.GetType()}.");
					break;
			}
		}
	}
}
