// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Player_PlayerHealthUI__char_46_SetHealthPerc_3423dc07_9f81_4726_82b9_9f0cdcad84cf : IEntityCommand
	{
		public float perc;

		public MessageTarget Routing => MessageTarget.AuthorityOnly;
		public uint GetComponentType() => Definition.InternalPlayer_PlayerHealthUI__char_46_SetHealthPerc_3423dc07_9f81_4726_82b9_9f0cdcad84cf;

		public Player_PlayerHealthUI__char_46_SetHealthPerc_3423dc07_9f81_4726_82b9_9f0cdcad84cf
		(
			float dataperc
		)
		{
			perc = dataperc;
		}

		public static void Serialize(Player_PlayerHealthUI__char_46_SetHealthPerc_3423dc07_9f81_4726_82b9_9f0cdcad84cf commandData, IOutProtocolBitStream bitStream)
		{
			bitStream.WriteFloat(commandData.perc, FloatMeta.NoCompression());
		}

		public static Player_PlayerHealthUI__char_46_SetHealthPerc_3423dc07_9f81_4726_82b9_9f0cdcad84cf Deserialize(IInProtocolBitStream bitStream)
		{
			var dataperc = bitStream.ReadFloat(FloatMeta.NoCompression());

			return new Player_PlayerHealthUI__char_46_SetHealthPerc_3423dc07_9f81_4726_82b9_9f0cdcad84cf
			(
				dataperc
			){};
		}
	}
}
