// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Player_PlayerHealthUI__char_46_ShowGrenadeKey_2c49cf3f_2ada_40d2_a08e_e94f1a8811fc : IEntityCommand
	{
		public bool show;

		public MessageTarget Routing => MessageTarget.AuthorityOnly;
		public uint GetComponentType() => Definition.InternalPlayer_PlayerHealthUI__char_46_ShowGrenadeKey_2c49cf3f_2ada_40d2_a08e_e94f1a8811fc;

		public Player_PlayerHealthUI__char_46_ShowGrenadeKey_2c49cf3f_2ada_40d2_a08e_e94f1a8811fc
		(
			bool datashow
		)
		{
			show = datashow;
		}

		public static void Serialize(Player_PlayerHealthUI__char_46_ShowGrenadeKey_2c49cf3f_2ada_40d2_a08e_e94f1a8811fc commandData, IOutProtocolBitStream bitStream)
		{
			bitStream.WriteBool(commandData.show);
		}

		public static Player_PlayerHealthUI__char_46_ShowGrenadeKey_2c49cf3f_2ada_40d2_a08e_e94f1a8811fc Deserialize(IInProtocolBitStream bitStream)
		{
			var datashow = bitStream.ReadBool();

			return new Player_PlayerHealthUI__char_46_ShowGrenadeKey_2c49cf3f_2ada_40d2_a08e_e94f1a8811fc
			(
				datashow
			){};
		}
	}
}
