// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.SimulationFrame;
	using Coherence.Entity;
	using Coherence.Utils;
	using Coherence.Brook;
	using Coherence.Toolkit;
	using UnityEngine;

	public struct Player__char_32_1_UnityEngine__char_46_Rigidbody_6402874779665503713 : ICoherenceComponentData
	{
		public Vector3 velocity;
		public Vector3 angularVelocity;

		public override string ToString()
		{
			return $"Player__char_32_1_UnityEngine__char_46_Rigidbody_6402874779665503713(velocity: {velocity}, angularVelocity: {angularVelocity})";
		}

		public uint GetComponentType() => Definition.InternalPlayer__char_32_1_UnityEngine__char_46_Rigidbody_6402874779665503713;

		public const int order = 0;

		public int GetComponentOrder() => order;

		public AbsoluteSimulationFrame Frame;
	

		public void SetSimulationFrame(AbsoluteSimulationFrame frame)
		{
			Frame = frame;
		}

		public AbsoluteSimulationFrame GetSimulationFrame() => Frame;

		public ICoherenceComponentData MergeWith(ICoherenceComponentData data, uint mask)
		{
			var other = (Player__char_32_1_UnityEngine__char_46_Rigidbody_6402874779665503713)data;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				velocity = other.velocity;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				angularVelocity = other.angularVelocity;
			}
			mask >>= 1;
			return this;
		}

		public static void Serialize(Player__char_32_1_UnityEngine__char_46_Rigidbody_6402874779665503713 data, uint mask, IOutProtocolBitStream bitStream)
		{
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteVector3((data.velocity.ToCoreVector3()), FloatMeta.NoCompression());
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				bitStream.WriteVector3((data.angularVelocity.ToCoreVector3()), FloatMeta.NoCompression());
			}
			mask >>= 1;
		}

		public static (Player__char_32_1_UnityEngine__char_46_Rigidbody_6402874779665503713, uint, uint?) Deserialize(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new Player__char_32_1_UnityEngine__char_46_Rigidbody_6402874779665503713();
	
			if (bitStream.ReadMask())
			{
				val.velocity = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}
			if (bitStream.ReadMask())
			{
				val.angularVelocity = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000010;
			}
			return (val, mask, null);
		}
		public static (Player__char_32_1_UnityEngine__char_46_Rigidbody_6402874779665503713, uint, uint?) DeserializeArchetypePlayer__char_32_1_62c26d239a795ba4eb3243cd969e8671_Player__char_32_1_UnityEngine__char_46_Rigidbody_6402874779665503713_LOD0(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new Player__char_32_1_UnityEngine__char_46_Rigidbody_6402874779665503713();
			if (bitStream.ReadMask())
			{
				val.velocity = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000001;
			}
			if (bitStream.ReadMask())
			{
				val.angularVelocity = (bitStream.ReadVector3(FloatMeta.NoCompression())).ToUnityVector3();
				mask |= 0b00000000000000000000000000000010;
			}

			return (val, mask, 0);
		}

		/// <summary>
		/// Resets byte array references to the local array instance that is kept in the lastSentData.
		/// If the array content has changed but remains of same length, the new content is copied into the local array instance.
		/// If the array length has changed, the array is cloned and overwrites the local instance.
		/// If the array has not changed, the reference is reset to the local array instance.
		/// Otherwise, changes to other fields on the component might cause the local array instance reference to become permanently lost.
		/// </summary>
		public void ResetByteArrays(ICoherenceComponentData lastSent, uint mask)
		{
			var last = lastSent as Player__char_32_1_UnityEngine__char_46_Rigidbody_6402874779665503713?;
	
		}
	}
}