// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Player_PlayerHealthUI__char_46_SetScoreCounter_2e74d780_b93f_4184_ac85_dca720aac870 : IEntityCommand
	{
		public int val;

		public MessageTarget Routing => MessageTarget.AuthorityOnly;
		public uint GetComponentType() => Definition.InternalPlayer_PlayerHealthUI__char_46_SetScoreCounter_2e74d780_b93f_4184_ac85_dca720aac870;

		public Player_PlayerHealthUI__char_46_SetScoreCounter_2e74d780_b93f_4184_ac85_dca720aac870
		(
			int dataval
		)
		{
			val = dataval;
		}

		public static void Serialize(Player_PlayerHealthUI__char_46_SetScoreCounter_2e74d780_b93f_4184_ac85_dca720aac870 commandData, IOutProtocolBitStream bitStream)
		{
			bitStream.WriteIntegerRange(commandData.val, 32, -2147483648);
		}

		public static Player_PlayerHealthUI__char_46_SetScoreCounter_2e74d780_b93f_4184_ac85_dca720aac870 Deserialize(IInProtocolBitStream bitStream)
		{
			var dataval = bitStream.ReadIntegerRange(32, -2147483648);

			return new Player_PlayerHealthUI__char_46_SetScoreCounter_2e74d780_b93f_4184_ac85_dca720aac870
			(
				dataval
			){};
		}
	}
}
