// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Player_PlayerHealthUI__char_46_ShowChronoStatisKey_77eb4f99_86da_4989_8faa_de4dd4bd6189 : IEntityCommand
	{
		public bool show;

		public MessageTarget Routing => MessageTarget.AuthorityOnly;
		public uint GetComponentType() => Definition.InternalPlayer_PlayerHealthUI__char_46_ShowChronoStatisKey_77eb4f99_86da_4989_8faa_de4dd4bd6189;

		public Player_PlayerHealthUI__char_46_ShowChronoStatisKey_77eb4f99_86da_4989_8faa_de4dd4bd6189
		(
			bool datashow
		)
		{
			show = datashow;
		}

		public static void Serialize(Player_PlayerHealthUI__char_46_ShowChronoStatisKey_77eb4f99_86da_4989_8faa_de4dd4bd6189 commandData, IOutProtocolBitStream bitStream)
		{
			bitStream.WriteBool(commandData.show);
		}

		public static Player_PlayerHealthUI__char_46_ShowChronoStatisKey_77eb4f99_86da_4989_8faa_de4dd4bd6189 Deserialize(IInProtocolBitStream bitStream)
		{
			var datashow = bitStream.ReadBool();

			return new Player_PlayerHealthUI__char_46_ShowChronoStatisKey_77eb4f99_86da_4989_8faa_de4dd4bd6189
			(
				datashow
			){};
		}
	}
}
