// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Player_PlayerHealthUI__char_46_ShowWaveIncomingText_25df724b_bc98_4af5_8ddd_3ee81431235d : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.AuthorityOnly;
		public uint GetComponentType() => Definition.InternalPlayer_PlayerHealthUI__char_46_ShowWaveIncomingText_25df724b_bc98_4af5_8ddd_3ee81431235d;

		public static void Serialize(Player_PlayerHealthUI__char_46_ShowWaveIncomingText_25df724b_bc98_4af5_8ddd_3ee81431235d commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Player_PlayerHealthUI__char_46_ShowWaveIncomingText_25df724b_bc98_4af5_8ddd_3ee81431235d Deserialize(IInProtocolBitStream bitStream)
		{

			return new Player_PlayerHealthUI__char_46_ShowWaveIncomingText_25df724b_bc98_4af5_8ddd_3ee81431235d
			(
			){};
		}
	}
}
