// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Player_PlayerHealthUI__char_46_SetComboMeterF_43f3d8ae_2c11_4a8a_972f_1c89f31d8f86 : IEntityCommand
	{
		public float perc;
		public bool animate;

		public MessageTarget Routing => MessageTarget.AuthorityOnly;
		public uint GetComponentType() => Definition.InternalPlayer_PlayerHealthUI__char_46_SetComboMeterF_43f3d8ae_2c11_4a8a_972f_1c89f31d8f86;

		public Player_PlayerHealthUI__char_46_SetComboMeterF_43f3d8ae_2c11_4a8a_972f_1c89f31d8f86
		(
			float dataperc,
			bool dataanimate
		)
		{
			perc = dataperc;
			animate = dataanimate;
		}

		public static void Serialize(Player_PlayerHealthUI__char_46_SetComboMeterF_43f3d8ae_2c11_4a8a_972f_1c89f31d8f86 commandData, IOutProtocolBitStream bitStream)
		{
			bitStream.WriteFloat(commandData.perc, FloatMeta.NoCompression());
			bitStream.WriteBool(commandData.animate);
		}

		public static Player_PlayerHealthUI__char_46_SetComboMeterF_43f3d8ae_2c11_4a8a_972f_1c89f31d8f86 Deserialize(IInProtocolBitStream bitStream)
		{
			var dataperc = bitStream.ReadFloat(FloatMeta.NoCompression());
			var dataanimate = bitStream.ReadBool();

			return new Player_PlayerHealthUI__char_46_SetComboMeterF_43f3d8ae_2c11_4a8a_972f_1c89f31d8f86
			(
				dataperc,
				dataanimate
			){};
		}
	}
}
